name: flutter_android_broadcasts
description: A plugin for sending and receiving broadcasts with Android intents and iOS notifications.
version: 0.3.0

repository: https://github.com/krikristoophe/flutter_android_broadcasts

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.kevlatus.flutter_broadcasts
        pluginClass: FlutterBroadcastsPlugin
      ios:
        pluginClass: FlutterBroadcastsPlugin
